### ISSUE TITLE
Just a suggestion 

### ISSUE THREAD

**Issue by apprahuman** [faiyazahmad07/xss_vibes#1]
Hey Faiyaz, I see the output file, it contains only the vulnerable urls, and we do not know which payload worked, is it possible to make the output with payload used, will be helpful. overall nice work guys

**Comment by faiyazahmad07** [comment]
Yes, We are working on it and will hopefully fix it in the next release

**Comment by faiyazahmad07** [comment]
Hi, We've fixed this issue.

**Comment by apprahuman** [comment]
That was fast.. awesome
