### ISSUE TITLE
Problem While adding Payload in .json

### ISSUE THREAD

**Issue by 0xbitsnbytes** [faiyazahmad07/xss_vibes#6]
I tired including more payload in payload.json.
It has become difficult . I want to use my custom payload list or One different file for adding payload in this code

**Comment by faiyazahmad07** [comment]
Hi, Thanks for raising this issue. Could you please tell me more about it? And if possible, attach a screenshot or a video for better understanding!
Thanks,
Faiyaz Ahmad

**Comment by faiyazahmad07** [comment]
Hi, I hope you are doing well. Since there's not update from your side regarding this issue, I am marking this one as Completed.
Thank you,
Faiyaz Ahmad

**Comment by 0xbitsnbytes** [comment]
I'm really sorry I was out of valley this week and sorry for trouble I was trying to use my custom payload by adding it in payloads.json which I found it to be more difficult ,So l wanted to use payload list using seclist, Which later I found that 
-w can be used , I'm really sorry for trouble and I will improve my mistake before creating any request in future
