### ISSUE TITLE
Error install requirement

### ISSUE THREAD

**Issue by toriousayo** [faiyazahmad07/xss_vibes#7]
There is a typographical error in the command `pip3 install -r requirement`. It returns the error `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirement'`.

The correct command however should be `pip3 install -r requirements` which will then go ahead and install the file.

**Comment by faiyazahmad07** [comment]
Hi, Thanks for raising this issue. We've fixed it and it should be "requirements" in the readme.md file.
Regards
Faiyaz Ahmad
