### ISSUE TITLE
LOADING PAYLOAD

### ISSUE THREAD

**Issue by shuvonsec** [faiyazahmad07/xss_vibes#8]
LOADING PAYLOAD FILE payloads.json but nothing is shown on my terminal, what can I do now?
There are no payloads shown on my terminal.
![Capture](https://github.com/faiyazahmad07/xss_vibes/assets/83355567/c9be23d8-6cd2-4473-b824-039ef7ab3071)

**Comment by faiyazahmad07** [comment]
Hi, could you please provide more details
